### ISSUE TITLE
You got some } missing

### ISSUE THREAD

**Issue by CA6** [XxSpiritDuoxX/Advance-Mod#3]
Tried to load up the latest version and 
![Mindustry_2020-01-05-14-57-26](https://user-images.githubusercontent.com/47131094/71787397-0f9cf580-2fcc-11ea-898e-bd15b82de48c.png)

![Mindustry_2020-01-05-14-57-32](https://user-images.githubusercontent.com/47131094/71787395-057af700-2fcc-11ea-9c86-6083a40fe085.png)

**Comment by XxSpiritDuoxX** [comment]
Sorry for the late reply,ill rush the newest update and release it
today,ill work on this fix and release the playable one today,v5 (or
latest) will arrive in a few days,i have not noticed this because of school
